# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Builds tensor_msgs ROS 2 interface library."""

load(
    "@com_github_mvukov_rules_ros2//ros2:interfaces.bzl",
    "c_ros2_interface_library",
    "cpp_ros2_interface_library",
    "py_ros2_interface_library",
    "ros2_interface_library",
)

ros2_interface_library(
    name = "tensor_msgs",
    srcs = glob(["msg/*.msg"]),
    visibility = ["//visibility:public"],
    deps = ["@ros2_rcl_interfaces//:builtin_interfaces"],
)

c_ros2_interface_library(
    name = "c_tensor_msgs",
    visibility = ["//visibility:public"],
    deps = [":tensor_msgs"],
)

cpp_ros2_interface_library(
    name = "cpp_tensor_msgs",
    visibility = ["//visibility:public"],
    deps = [":tensor_msgs"],
)

py_ros2_interface_library(
    name = "py_tensor_msgs",
    visibility = ["//visibility:public"],
    deps = [":tensor_msgs"],
)
